#!/usr/bin/env python3
"""Generate a synthetic task corpus for the e2e stack.

The real OMJ material - the task PDFs and the statements transcribed from them -
is not part of this repository (see NOTICE), so the e2e suite must not depend on
it. This script fabricates a stand-in for every year/etap that has tracked
metadata in `data/tasks/`:

    e2e/fixtures/task_corpus/tasks/{year}/{etap}/e2e-{year}-{etap}.pdf
    e2e/fixtures/task_corpus/task_content/{year}/{etap}.json

`docker-compose.e2e.yml` mounts those two directories over `/app/tasks` and
`/app/data/task_content`, so the e2e API serves invented tasks with the project's
own metadata. Nothing here is derived from OMJ material.

The generated tree is git-ignored and regenerated by e2e/run-e2e.sh on every run.

Usage:
    python e2e/generate_task_fixtures.py
"""

import json
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TASKS_DATA_DIR = PROJECT_ROOT / "data" / "tasks"
FIXTURE_ROOT = Path(__file__).resolve().parent / "fixtures" / "task_corpus"
FIXTURE_PDF_DIR = FIXTURE_ROOT / "tasks"
FIXTURE_CONTENT_DIR = FIXTURE_ROOT / "task_content"


def make_pdf(lines: list[str]) -> bytes:
    """A minimal but structurally valid one-page PDF with a few lines of text."""
    text_ops = ["BT", "/F1 14 Tf", "72 720 Td", "18 TL"]
    for line in lines:
        escaped = line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        text_ops.append(f"({escaped}) Tj")
        text_ops.append("T*")
    text_ops.append("ET")
    stream = "\n".join(text_ops).encode("latin-1", "replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_pos = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_pos}\n%%EOF\n"
    ).encode()
    return bytes(out)


def synthetic_statement(year: str, etap: str, number: int) -> dict:
    """Invented statement - deliberately obvious, never OMJ text."""
    return {
        "title": f"Zadanie testowe {number} ({year} {etap})",
        "content": (
            f"To jest syntetyczna treść zadania {number} z {year} {etap}, "
            f"używana wyłącznie w testach e2e. "
            f"Wyznacz wszystkie liczby całkowite $n$ takie, że $n^2 + {number} < 100$."
        ),
    }


def main() -> int:
    if not TASKS_DATA_DIR.exists():
        print(f"No task metadata at {TASKS_DATA_DIR}", file=sys.stderr)
        return 1

    if FIXTURE_ROOT.exists():
        shutil.rmtree(FIXTURE_ROOT)

    etaps = 0
    tasks = 0

    for year_dir in sorted(TASKS_DATA_DIR.iterdir()):
        if not year_dir.is_dir():
            continue
        for etap_dir in sorted(year_dir.iterdir()):
            if not etap_dir.is_dir():
                continue
            numbers = []
            for task_file in sorted(etap_dir.glob("task_*.json")):
                with open(task_file, "r", encoding="utf-8") as f:
                    numbers.append(json.load(f)["number"])
            if not numbers:
                continue

            year, etap = year_dir.name, etap_dir.name

            # The PDF path recorded in the metadata points at the real corpus,
            # so rewrite nothing: instead publish the fixture under the exact
            # relative path the metadata expects.
            with open(sorted(etap_dir.glob("task_*.json"))[0], "r", encoding="utf-8") as f:
                pdf_meta = json.load(f)["pdf"]

            for kind, rel in pdf_meta.items():
                if not rel:
                    continue
                target = FIXTURE_PDF_DIR / Path(rel).relative_to("tasks")
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(
                    make_pdf(
                        [
                            f"OMJ Validator e2e fixture - {year} {etap} ({kind})",
                            "Synthetic document. Not OMJ material.",
                        ]
                        + [f"Zadanie {n}: tresc testowa." for n in numbers]
                    )
                )

            content_path = FIXTURE_CONTENT_DIR / year / f"{etap}.json"
            content_path.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "year": year,
                "etap": etap,
                "tasks": {str(n): synthetic_statement(year, etap, n) for n in numbers},
            }
            with open(content_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, ensure_ascii=False, indent=2)
                f.write("\n")

            etaps += 1
            tasks += len(numbers)

    pdfs = sum(1 for _ in FIXTURE_PDF_DIR.rglob("*.pdf"))
    print(f"Generated synthetic corpus: {tasks} tasks, {etaps} etaps, {pdfs} PDFs")
    print(f"  PDFs:       {FIXTURE_PDF_DIR}")
    print(f"  Statements: {FIXTURE_CONTENT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
